handleGHRelease: true
releaseType: simple
bumpMinorPreMajor: true
bumpPatchForMinorPreMajor: true
draft: true
changelogSections:
  - type: "feat",
    section: "Added",
    hidden: false
  - type: "change",
    section: "Changed",
    hidden: false
  - type: "deprecate",
    section: "Deprecated",
    hidden: false
  - type: "fix",
    section: "Fixed",
    hidden: false
  - type: "remove",
    section: "Removed",
    hidden: false
  - type: "security",
    section: "Security",
    hidden: false